services:
  - type: web
    name: wex-theory
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: wex-theory-db
          property: connectionString

databases:
  - name: wex-theory-db
    databaseName: wex_theory
    plan: free
